ingest:
  steps: [collection, type, ingestmethod, metadata]
  step_data:
    collection: [ingestcollection]
    type: [ingesttype]
    ingestmethod: [ingestmethod]
interface:
  languages: [en, ga]
dri:
  files: dri_files
queue:
  audio: [CreateChecksums, VirusScan, VerifyAudio, CreateMp3, CreateOgg]
  pdfdoc: [CreateChecksums, VirusScan, VerifyPdf, FullTextIndex]
