interface:
  languages: [en, ga]
dri:
  password: CHANGEME
  files: dri_files/data
  uploads: dri_files/uploads
  downloads: dri_files/downloads
plugins:
  ffmpeg_path: /usr/local/bin/ffmpeg
  fits_path: /opt/local/fits/fits.sh
restrict:
  mime_types:
    image: ['image/png','image/jpeg', 'image/jpg', 'image/jp2', 'image/bmp', 'image/gif', 'image/tiff']
    text: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/plain', 'text/xml']
    pdf: ['application/pdf', 'application/x-pdf']
    audio: ['audio/mp3', 'audio/mpeg', 'audio/mpeg3', 'audio/mp2', 'audio/wav', 'audio/x-wave', 'audio/x-wav', 'audio/ogg']
    video: ['video/mpeg', 'video/mp4', 'video/webm', 'video/x-msvideo', 'video/avi', 'video/quicktime', 'application/mxf']
storage:
  driver: s3_interface
S3:
  server: http://localhost:8081
  use_ssl: false
  access_key_id: anything
  secret_access_key: anything
  expiry: 604800
data:
  types: [Sound, MovingImage, Image, Text]
doi:
  enable: "false"
iiif:
  server: http://localhost:3000/iiif
