interface:
  languages: [en, ga]
dri:
  password: CHANGEME
  files: dri_files/data
  uploads: dri_files/uploads
  downloads: dri_files/downloads
plugins:
  fits_path: /opt/local/fits/fits.sh
  libreoffice_path: '/usr/bin/libreoffice'
restrict:
  mime_types:
    image: ['image/png','image/jpeg', 'image/jpg', 'image/jp2', 'image/bmp', 'image/gif', 'image/tiff']
    text: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/plain', 'text/xml', 'application/msword']
    pdf: ['application/pdf', 'application/x-pdf']
    audio: ['audio/mp3', 'audio/mpeg', 'audio/mpeg3', 'audio/mp2', 'audio/wav', 'audio/x-wave', 'audio/x-wav', 'audio/ogg']
    video: ['video/mpeg', 'video/mp4', 'video/webm', 'video/x-msvideo', 'video/avi', 'video/quicktime', 'application/mxf']
    tabular: ['application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.spreadsheetml.template', 'application/vnd.ms-excel.sheet.macroEnabled.12', 'application/vnd.ms-excel.template.macroEnabled.12', 'application/vnd.ms-excel.addin.macroEnabled.12', 'application/vnd.ms-excel.sheet.binary.macroEnabled.12']
storage:
  driver: s3_interface
downloads:
  directory: /tmp
S3:
  server: http://localhost:8081
  use_ssl: false
  access_key_id: anything
  secret_access_key: anything
  expiry: 604800
doi:
  enable: "false"
iiif:
  server: http://localhost:3000/iiif
analytics:
  disable: true
