ingest:
  steps: [collection, object_type, ingestmethod, metadata]
  step_data:
    collection: [ingestcollection]
    object_type: [ingesttype]
    ingestmethod: [ingestmethod]
interface:
  languages: [en, ga]
dri:
  files: dri_files
  logos: dri_files/logos
plugins:
  ffmpeg_path: /opt/local/bin/ffmpeg
restrict:
  mime_types:
    image: ['image/png','image/jpeg', 'image/jpg', 'image/jp2', 'image/bmp', 'image/gif', 'image/tiff' ]
    text: ['application/pdf', 'application/x-pdf']
    pdf: ['application/pdf', 'application/x-pdf']
    audio: ['audio/mp3', 'audio/mpeg', 'audio/mpeg3', 'audio/mp2', 'audio/wav', 'audio/x-wave', 'audio/x-wav', 'audio/ogg']
    video: ['video/mpeg', 'video/mp4', 'video/webm', 'video/x-msvideo', 'video/avi', 'video/quicktime', 'application/mxf']
S3:
  server: 10.0.1.201
  access_key_id: FIXME
  secret_access_key: FIXME
surrogates:
  sound: [mp3, ogg]
  text: [thumbnail]
  image: [thumbnail]
data:
  cover_image_bucket: coverimages
  types: [Sound, MovingImage, Image, Text]
