ingest:
  steps: [collection, object_type, ingestmethod, metadata]
  step_data:
    collection: [ingestcollection]
    object_type: [ingesttype]
    ingestmethod: [ingestmethod]
interface:
  languages: [en, ga]
dri:
  files: dri_files
  logos: dri_files/logos
queue:
  audio: [CreateBucket, CreateChecksums, CreateMp3, CreateOgg]
  pdfdoc: [CreateBucket, CreateChecksums, FullTextIndex]
plugins:
  ffmpeg_path: /opt/local/bin/ffmpeg
mp3_web_quality_out_options:
  codec: # default is for ffmpeg to auto-detect appropriate codec, this should be good for most scenarios
  strip_metadata: "yes" # default is to preserve global metadata
  channel: "2" # default is same as input file
  bitrate: "96k" # default is same as input file
  frequency: "44100" # default is same as input file
ogg_web_quality_out_options:
  codec: libvorbis # Default for ogg will produce very large files
  strip_metadata: "yes" # default is preserve global metadata
  channel: "2" # default is same as input file
  bitrate: "96k" # default is same as input file
  frequency: "44100" # default is same as input file
restrict:
  mime_types: [ "application/pdf", "application/x-pdf", "audio/mp3", "audio/mpeg", "audio/mpeg3", "audio/mp2", "image/tiff", "video/mp4" ]
S3:
  server: 10.0.1.201
  access_key_id: FIXME
  secret_access_key: FIXME
surrogates:
  Sound: [mp3_web_quality, ogg_web_quality]
  Document: [pdf]
data:
  types: [Audio, Article]
